update web-vault to v2022.12.0
dani-garcia/bw_web_builds pull request #105
Opened 2022-12-14 22:08 UTC by tessus

2022-12-16 05:54 UTC, GeekCornerGH approved these changes

2022-12-17 16:40 UTC, BlackDex requested changes
The patch file looks like an exact copy of `v2022.11.1.patch`.
While it does work, it isn't fully valid. There are some offsets different in the `v2022.12.0` patch.

Run the `make generate-patch` and force-push it so it will have a fully clean patch matching the correct offset. This could help with the next round of changes if the offset changes further.

2022-12-17 19:55 UTC, tessus commented
Done.

It's interesting though that the apply script did not mention it. I think it only said `patch xxx applied successfully`. Or I missed it, because it was just one occasion where the offset waws different:

```diff
-index 115d53401..e62638e35 100644
+index bb8bf7707..49f2444c8 100644
 --- a/apps/web/src/app/core/web-platform-utils.service.ts
 +++ b/apps/web/src/app/core/web-platform-utils.service.ts
-@@ -188,11 +188,11 @@ export class WebPlatformUtilsService implements PlatformUtilsService {
+@@ -192,11 +192,11 @@ export class WebPlatformUtilsService implements PlatformUtilsService {
    }
```

2022-12-17 19:57 UTC, tessus commented
@BlackDex for some reason it's not possibe to re-request a review.

2022-12-18 18:58 UTC, merged