rename to `Vaultwarden Web` and get rid of 404 page
dani-garcia/bw_web_builds pull request #138
Opened 2023-08-15 18:32 UTC by stefan0xC

It seems that in the next release, the translation key `pageTitle` will be removed (see https://github.com/bitwarden/clients/pull/5780) and replaced by a new one called `bitWebVault` where Bitwarden is hardcoded in the `messages.json` files. I would use that as opportunity to rectify the issue that @tessus has brought up in #131 by reverting the change and renaming the modified web-vault to `Vaultwarden Web` instead (omitting the last Vault as we already have that in Vaultwarden itself).

If we want to credit Bitwardenı® Web Vault in the client itself (which arguably we don't have to), I think we could add another row to the footer, where we can have a better phrase without parentheses, e.g.

>  Vaultwarden is an unofficial rewrite of the Bitwarden® server. The Vaultwarden Web client is a modified version of the Bitwarden® Web Vault.
> The Vaultwarden project is not associated with the Bitwarden® project nor Bitwarden Inc.

![vaultwarden-footer](https://github.com/dani-garcia/bw_web_builds/assets/509385/98e27264-4052-44f9-a9ed-f9cdf559ea12)

Since we don't use this 404 page anymore, I think it would make sense to remove it from the patch file and just don't ship it in `apps/web/webpack.config.js`.

And because I have been testing a different way of managing the changes (see #137), I would appreciate it, if we could run a linter and prettier before creating a patch, so it's easier to keep the changes in sync. I mean, those are mostly superficial changes but I think they don't really hurt either and we also require `cargo fmt` and `clippy` for Vaultwarden.

2023-08-15 18:53 UTC, tessus commented
Have you also tested how it looks like after logging in?

The long text is actually nice on the login page, but I doubt it would looks nice in the rest of the app:

<img width="1028" alt="image" src="https://github.com/dani-garcia/bw_web_builds/assets/223439/3b277da2-8039-407a-b6f2-ca44cb8dab6e">

2023-08-15 20:17 UTC, stefan0xC commented
I've not yet added the text so currently it would look like this:
![vaultwarden-web-footer](https://github.com/dani-garcia/bw_web_builds/assets/509385/19434835-948d-442e-83a9-17d4f323afaa)

If we just insert the same text into the middle colum (without the break), it would look like this:
![vaultwarden-footer-with-notice](https://github.com/dani-garcia/bw_web_builds/assets/509385/af74a61b-b384-48aa-8bf7-1493208421b6)

To improve that. we could add `col-8` as class to the div so it has more space:
![vaultwarden-footer-with-alternative-notice](https://github.com/dani-garcia/bw_web_builds/assets/509385/ec52083f-1d67-497c-9454-9e8a8258afca)

2023-08-15 20:23 UTC, BlackDex commented
I personally would still like to have some notice of the copyright or origin that the web-vault is a fork from Bitwarden®. Mostly to still indicate a link.

But, it doesn't have to be that long though haha.
I'm also not sure what a good alternative would be right now.

2023-08-15 20:31 UTC, tessus commented
I think the long text would be great for the login page. But only for the login page.

In the rest of the app, I would just 
- not populate the middle column at all
- use a short text in the middle column: `(unofficial Bitwarden® server)`. And in this case the parenthesis are ok (I think I would prefer this one)

2023-08-15 20:32 UTC, stefan0xC commented
> But, it doesn't have to be that long though haha.

Personally, I think it would be fair if we could make the text even longer by also providing a plea to support the on-going development of the Bitwarden® project by getting a Premium subscription. :smirk:

2023-08-15 21:29 UTC, tessus commented
[v2023.8.0](https://github.com/bitwarden/clients/releases/tag/web-v2023.8.0) was just released.

2023-08-15 21:50 UTC, tessus commented
I am still waiting for some feedback about the footer in the app (not the login page).

Is it even possible to have different text on the login page and the rest of the app?
As mentioned before, the long text looks really bad in the app. Please don't use this in the app.

But it looks great on the login page (the first image you poated).

2023-08-15 21:55 UTC, stefan0xC commented
Yes, those are two different files (`footer.component.html` vs `frontend-layout.component.html`), so it's possible to have different texts.

Before updating to v2023.8.0 I've already added the third version for now (until I get or have a better suggestion for how to display it better) because I think it looks better than having nothing and I'm not sure I like a free-floating "(unofficial Bitwarden® server)"

2023-08-15 22:01 UTC, tessus commented
I certainly like the `(unofficial Bitwarden® server)` in the middle column best. I really dislike the long text in the middle. So in that case, why not use the previous layout for the app.

left: Vaultwarden Web (unofficial Bitwarden® server)
right: Version 2023.8.0

if you don't like that, how about:

left: Vaultwarden Web
middle: running on Vaultwarden, an unofficial Bitwarden® server
right: Version 2023.8.0

2023-08-16 19:50 UTC, tessus commented
I don't want to be ungrateful for your attempt to make the long text shorter, but this doesn't look like a footer, nor does it seem any shorter.
Try like 10-12 words in total. Your idea is too overwhelming for a footer and requires to spend cognitive load on something that is basically unimportant.

I really do no understand why you want to plaster a banner (this is what it rather looks like) on every single page in the web app. Or maybe it is your idea of annoy people so that they won't misunderstand versioning. The operative word here is "annoy". It has a nag screen feel to it.

A footer should be unobtrusive. Do the examples (all but the one where you omitted the long text) strike you as discreet?

Please tell me what you think of my [suggestions](https://github.com/dani-garcia/bw_web_builds/pull/138#issuecomment-1679678871)? Why are they not ok? I checked how they look, and they look great for a footer. They tell you everything there is to know.

The long text is more like documentation or an appeal to people to finally understand the point you are trying to make. This is why it is great for the login page. It is the first thing people see. If they haven't read it there, they won't read it in th app either. It just makes the whole experience more clunky and annoying for people who know what the text means but have to see that text on every operation in the app.
This is really bad UX. Don't take this personal, I am not trying to belittle your effort.

I have mentioned this before and it is not only my opinion but also a fact:

Making the obvious more obvious will not yield a different result.

If people are ignorant or think they know everything, they won't read documentation, or a wiki page, or an annoying footer, or an issue template.
I have tried the same thing you are trying to do with a real banner in a forum, a template in certain categories of a forum, and I have also used issue templates. Guess what, all these things didn't work. People delete the templates, or even keep the templates and just ignore them. I am just trying to explain that a long text won't change anything, but to annoy people who do not need to read the text, because they already understand the components and versioning concept.

2023-08-16 21:08 UTC, stefan0xC commented
As said in the beginning, I'm totally okay with having no text there but I also don't think that a longer text is that distracting or bad UI as you make it out to be. Please don't overexaggerate the issue because you disagree with me.

Maybe I was unclear but I have suggested those three lines with reasons, which is why I have not adopted different ones or taking your suggestions seriously. Sorry, about that but I did not see the point. 

Trying to be serious for a moment and defending my proposal and why I am suggesting three short sentences instead of being content with something like "Vaultwarden Web (unofficial Bitwarden® server)", here's what I'm thinking:

1. They clearly identify what the users are looking at without calling the web-client a server.
2. We make our relations to the Bitwarden® project clear in proper accordance [with their trademark guidelines](https://github.com/bitwarden/server/blob/master/TRADEMARK_GUIDELINES.md) and the requirements of the GPLv3.
3. We do that even if we legally don't have to, since it's only fair and in the spirit of cooperation.

Legally, the trademark guidelines would be fulfilled by not mentioning Bitwarden at all. The GPLv3 (§ 5.) also states that
> d) If the work has interactive user interfaces, each must display Appropriate Legal Notices; however, if the Program has interactive interfaces that do not display Appropriate Legal Notices, your work need not make them do so.

However since you repeated something you already said in #131 and what I do have to make clear is that my changes are not to imply that our users are ignorant or stupid. So please stop suggesting that. Also I am not the one who decides what gets added (I'm just a contributor making suggestions). It may just be a difference of opinion or aesthetics and I definitely disagree with your assessments. But since I agree with you that is not that important I don't really see the point in arguing this further with you (especially if you want to insult other users).

2023-08-16 21:53 UTC, tessus commented
Just to be clear (and this is important to me), I was not insulting anyone, I was stating a fact. Please look up the words (ignorance and stupidity) in a dictionary and check, whether they fit or not. Although stupidity might be too harsh when you look at that word alone, you have to read it in context with ignorance, as it was meant.
How is someone who ignores issue templates, documentation, and READMEs not ignorant?
If someone is offended, why do you think that is? 

Anyway, this is my last comment on that matter. This is way off-topic and I certainly did not want to offend anyone or have the dicussion go in this direction. But I can't be made the bad guy, because I stated a fact. Please don't twist my words or interpret something that isn't there.

When it comes to the footer we apparently won't agree on it ever. 
Luckily I can just create my own version and all is good. 

I know that you do not make the decisions, but you have been an avid contributor to this project and the project owners will listen to you more than they would to me.
So I wanted to at least voice my concerns and my opinion.

2023-08-17 17:22 UTC, stefan0xC commented
Back to topic, I think  we have multiple options from minimalist to more verbose for the footer:

I think the minimalist change (i.e. "_Vaultwarden Web_" on the left, "_Version v2023.8.0_" on the right) serves as the basis of the following suggestions and I would like to say that I slightly prefer it over the current/previous options but not very much.

I think that I can also live with slight variation of @tessus' last suggestion (i.e. "_running on Vaultwarden, an unofficial [rewrite of the] Bitwarden® server_". I am not particularly fond of it and I would rather we brainstorm some more or get some more perspectives before settling on this one but I'd definitely prefer it over "_Vaultwarden Web (unofficial Bitwarden® server_)" (or the current/previous version)...

Looking back to the suggestions from the previous PR, maybe we can do something like a mix. I.e. explain about Vaultwarden (the server) on the left and Vaultwarden Web (the client) on the right?

An alternative suggestion would be to use a way to also build the web-client when we build vaultwarden and insert the version into the footer.

As already stated my most preferred option at the moment would be to use the same three statements on both footers (so we can mention "Bitwarden®" as often as possible or see my better reasons above :point_up: ), which I have tried to reduce to the essentials I would like to convey: "_Vaultwarden is an unofficial Bitwarden® server. Vaultwarden Web is a modified version of the Bitwarden® Web Vault. The Vaultwarden project is not associated with the Bitwarden® project nor Bitwarden, Inc._" To make the footer less obtrusive we could also reduce the font-size and/or the whitespace around it (which is rather high with a padding of 40px).

However, I agree that it might not be necessary to use the same statements in both footers. So maybe we can save some space by not using the last sentence? (Which is probably the most dispensable one because I rather we mention both Vaultwarden as well as the modifications to the Bitwarden® Web-Vault and not something that is probably superfluous).

2023-08-18 22:59 UTC, stefan0xC commented
> maybe we can save some space by not using the last sentence? 

_Vaultwarden is an unofficial rewrite of the Bitwarden® server using a modified version of the Bitwarden® Web Vault._

If we were okay with such a statement the footer would (currently) look like this
![Proposal at 2023-08-19 at 00-53-04 Vaultwarden Web](https://github.com/dani-garcia/bw_web_builds/assets/509385/fd2a98dc-fdb0-4fc8-af2e-882307d98661)

2023-08-24 20:02 UTC, stefan0xC commented
While testing the [`web-v2023.8.2`](https://github.com/bitwarden/clients/releases/tag/web-v2023.8.2) release I noticed that the organization creation has changed between `web-v2023.7.1` and `web-v2023.8.0`, so I'll have to take another look at it. I'm not sure what the web-vault expects (i.e.[ `getPlans()` ](https://github.com/bitwarden/clients/blob/627b39f6f378528107eacaa4053d79f8f3c14608/libs/common/src/services/api.service.ts#L891-L894)asks for `/plans/all` instead of `/plans/`).

2023-08-26 23:23 UTC, tessus commented
So does this mean that the org creation will fail on 2023.8.2, if https://github.com/dani-garcia/vaultwarden/pull/3797 has not been merged?

2023-08-27 10:46 UTC, stefan0xC commented
It will not work and say something along the line that you have not selected a plan. (And you can't because the required component is just missing and I have not figured out how to make the API call obsolete.)

2023-08-29 22:56 UTC, stefan0xC commented
after testing my 2fa policy removal change with `web-v2023.8.2` i noticed that it also expects a UserDecryptionOptions field in the `/api/connect/token` response on a successful login (something like dani-garcia/vaultwarden#3813) so that the vault is shown instead of the `set-password` component.
![Screenshot 2023-08-29 at 23-36-26 Set master password Vaultwarden Web](https://github.com/dani-garcia/vaultwarden/assets/509385/402a9a7c-b485-47c7-a450-65a4f2382dd2)

2023-08-31 16:21 UTC, BlackDex requested changes
Overall it looks good.
I have not build it my self, and browsed through it though.

2023-08-31 17:14 UTC, stefan0xC commented on patches/v2023.7.1.patch
I've removed the changes to the patch file.

2023-08-31 17:14 UTC, stefan0xC commented on patches/v2023.8.2.patch
> ++      A modified version of the Bitwarden® Web Vault for Vaultwarden
Done.

2023-08-31 17:15 UTC, stefan0xC commented on patches/v2023.8.2.patch
> ++  </div>
Done.

2023-08-31 17:22 UTC, stefan0xC commented on patches/v2023.8.2.patch
> ++<!DOCTYPE html>
Maybe. I am not sure this is important, so I have reverted the change.

2023-08-31 17:42 UTC, BlackDex commented
Ok, i think this works, I'm not fully sure on the text in the middle, but i'm also not against it. Not sure what @dani-garcia thinks about this change?

Regarding the `npm audit fix` discussed somewhere else (can't find it right now that quickly for some reason).
I think it's good to remove this from our builds, to keep stuff more the same as upstream Bitwarden.

I'm fine if you want to remove this via this PR.

2023-08-31 17:59 UTC, stefan0xC commented
okay, I've added a commit that removes the `npm audit fix` (so we can close #139)

2023-08-31 17:59 UTC, BlackDex approved these changes

2023-08-31 18:36 UTC, dani-garcia approved these changes
Looks good to me, thanks everyone!

2023-08-31 18:48 UTC, merged