revert patch to edit org info
dani-garcia/bw_web_builds pull request #155
Opened 2024-02-04 21:06 UTC by stefan0xC

Sorry, another issue introduced by me. 🫣

fixes [this external bug report](https://vaultwarden.discourse.group/t/cant-change-organization-name-and-emil/3318?u=stefan0xc)

2024-02-04 21:16 UTC, BlackDex commented
Luckily we didn't released 1.30.4 yet 😂

2024-02-04 21:26 UTC, stefan0xC commented
I think I'll have to get more familiar with the web-vault because the whole `isSelfHosted` stuff is very confusing to me. :sweat_smile:

2024-02-04 22:12 UTC, BlackDex commented
That is more because of the whole organization licensing part.
The non-self-hosted allows to create orgs without a license file, the self-hosted need a file.

So, we mimic a bit more the SaaS version of the web-vault this way.

2024-02-04 22:21 UTC, stefan0xC commented
Yeah, but I think it would be less confusing (at least to me) if it would default to `true` and we only made the necessary changes wherever we had to instead of pretending to be the cloud version and having to decide where it's necessary to revert the check for self hosted. :thinking:

2024-02-04 22:23 UTC, BlackDex commented
Worth looking into i think.

2024-02-05 12:29 UTC, BlackDex requested changes

2024-02-05 12:29 UTC, BlackDex commented on patches/v2024.1.2.patch
On line 35 and 36 you also did some inverting of the selfHosted value.
Maybe it's better to leave that as is, and put `return;` above the `if` statement?
And maybe add a comment there like `return; // flexible collections are not supported by Vaultwarden`

That way it's clear we do not support that part, and it will not break if somehow that values changes hehe ;).

2024-02-06 06:56 UTC, stefan0xC commented
I'll do a separate PR once this is merged for rewriting the patch file. Unless we are fine with changing the background color of the navbar? (A self hosted Bitwarden instance uses [a different background color](https://github.com/bitwarden/clients/blob/c97e5b3d1ffe201fe807896a22e4f731fba73d65/apps/web/src/app/layouts/navbar.component.html#L1) (`#1a3b66`) from the default `#175ddc` which I would change to the color we use in the /admin navbar, i.e. `#212529`)

2024-02-07 21:19 UTC, BlackDex approved these changes

2024-02-07 21:19 UTC, merged